Redo pom version
Using <release> in the POM seems to work in servers; using <source> and <target> crashes in apex server with a `NoClassDefFoundError: java/lang/constant/Constable`

There's a version compatibility problem that needs to be fixed.